name: Action on Pull Request
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main' 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  GITHUB_SHA: ${{ github.sha }}
  NEW_BRANCH_NAME: join(['DEPENDABOT','-', $GITHUB_SHA])
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
permissions:
  contents: write
  
jobs:
  run_if:
    if: startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo Renaming branch from $BRANCH_NAME to $NEW_BRANCH_NAME
      - run: gh api repos/novakps/$GH_REPOSITORY/branches/$BRANCH_NAME/rename -F new_name=$NEW_BRANCH_NAME
