name: Recreate dependabot Pull Request with renamed branch
on:
  workflow_dispatch: # testing only
  pull_request:
    types: [opened, reopened]
    branches:
      - main 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_BASE: ${{ github.event.pull_request.base.ref }}
  PR_URL: ${{github.event.pull_request.html_url}}
  PR_TITLE: ${{ github.event.pull_request.title }}
  PR_BODY: ${{ github.event.pull_request.body }}
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  run_if:
    if:  github.actor == 'dependabot[bot]' 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: generate new branch name from head sha of PR branch
        run: |
          branchSha=$(gh pr view "$PR_NUMBER" --json headRefOid --jq '.headRefOid')
          echo "NEW_BRANCH_NAME=DEPENDABOT-"${branchSha:0:10}"" >> $GITHUB_ENV
      - name: Rename base branch so it will work in our build system, should close original branch and PR
        run: gh api "repos/$GH_REPOSITORY/branches/$BRANCH_NAME/rename" --method POST -f "new_name=$NEW_BRANCH_NAME"    
      - name: create new PR from renamed branch
        run: |
          newPRURL=$(gh pr create -B "$PR_BASE" -H "$NEW_BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY")
          echo "NEW_PR_URL=$newPRURL" >> $GITHUB_ENV
      - name: comment on old PR linking to new PR
        run: gh pr comment "$PR_NUMBER" --body "Superceded by $NEW_PR_URL"

