name: Auto-approve dependabot Pull Requests
on:
  pull_request:
    types:
      - opened
    branches:
      - main 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_BASE: ${{ github.event.pull_request.base.ref }}
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  run_if:
    if:  github.actor == 'dependabot[bot]' || github.actor == 'novakps'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate new branch name from short git commit SHA
        run: |  
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "NEW_BRANCH_NAME=DEPENDABOT_$calculatedSha" >> $GITHUB_ENV
      - name: Rename base branch so it will work in our build system
        run: gh api "repos/$GH_REPOSITORY/branches/$BRANCH_NAME/rename" -f "new_name=$NEW_BRANCH_NAME"
      - name: Copy Title from original PR
        run: echo "PR_TITLE=A dummy title" >> $GITHUB_ENV
      - name: Copy Body from original PR
        run: echo "PR_BODY=A dummy body" >> $GITHUB_ENV
      - name:  Create new PR with renamed base branch
        run: gh pr create -B "$PR_BASE" -H "$NEW_BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY"
      - name: set auto-merge
        run: gh pr merge "$PR_NUMBER" --auto --delete-branch
      - name: approve dependabot PR
        run: gh pr review "$PR_NUMBER" --approve 

      
