name: Action on Pull Request
on:
  pull_request:
    types:
      - opened
    branches:
      - main 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  NEW_BRANCH_NAME: DEPENDABOT_${{ github.sha }}
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
permissions:
  contents: write
  
jobs:
  run_if:
    if: startsWith(BRANCH_NAME, 'dependabot/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Renaming branch from $BRANCH_NAME to $NEW_BRANCH_NAME"
      - run: echo $(gh api repos/$GH_REPOSITORY/branches/$BRANCH_NAME/rename -F new_name=$NEW_BRANCH_NAME)
      - run: $(gh api repos/$GH_REPOSITORY/branches/$BRANCH_NAME/rename -F new_name=$NEW_BRANCH_NAME)
