name: Action on open dependabot Pull Request
on:
  pull_request:
    types:
      - opened
    branches:
      - main 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  NEW_BRANCH_NAME: DEPS${{ github.sha }}
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.number }}
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  run_if:
    if: startsWith(github.head_ref, 'dependabot_')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Renaming branch from $BRANCH_NAME to $NEW_BRANCH_NAME"
      - run: gh api "repos/$GH_REPOSITORY/branches/$BRANCH_NAME/rename" -f "new_name=$NEW_BRANCH_NAME"
      - run: echo "Creating new PR from $PR_NUMBER for renamed branch"
      - run: gh pr create -B "$PR_BASE" -H "$NEW_BRANCH_NAME" --title "$PR_BASE" --body "$PR_TITLE"

      
