name: Auto-approve dependabot Pull Requests
on:
  pull_request:
    types:
      - opened
    branches:
      - main 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_BASE: ${{ github.event.pull_request.base.ref }}
  PR_URL: ${{github.event.pull_request.html_url}}
  PR_TITLE: ${{ github.event.pull_request.title }}
  PR_BODY: ${{ github.event.pull_request.body }}
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  run_if:
    if:  github.actor == 'dependabot[bot]' || github.actor == 'novakps'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: close PR
        run: gh pr close "$PR_NUMBER"
      - name: Calculate new branch name from short git commit SHA
        run: |  
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "NEW_BRANCH_NAME=DEPENDABOT_$calculatedSha" >> $GITHUB_ENV
      - name: Rename base branch so it will work in our build system
        run: gh api "repos/$GH_REPOSITORY/git/refs" --method POST -f ref="refs/heads/$NEW_BRANCH_NAME" -f sha="${{ github.sha }}"
      - name: create new PR from renamed branch
        run: gh pr create -B "$PR_BASE" -H "$NEW_BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY" --json number
      - name: approve new PR
        run: gh pr review --approve       


      
