name: Auto-approve dependabot Pull Requests
on:
  workflow_dispatch: # testing only
  pull_request:
    types: [opened, reopened]
    branches:
      - main 
env:
  BRANCH_NAME: ${{ github.head_ref }}
  GH_TOKEN: ${{ github.token }}
  GH_REPOSITORY: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_BASE: ${{ github.event.pull_request.base.ref }}
  PR_URL: ${{github.event.pull_request.html_url}}
  PR_TITLE: ${{ github.event.pull_request.title }}
  PR_BODY: ${{ github.event.pull_request.body }}
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  run_if:
    if:  github.actor == 'dependabot[bot]'  || github.actor == 'novakps'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: generate new branch name from head sha of PR branch
        run: |
          branchSha=$(gh pr view "$PR_NUMBER" --json headRefOid --jq '.headRefOid')
          echo "BRANCH_SHA=$branchSha" >> $GITHUB_ENV
          echo "NEW_BRANCH_NAME=DEPENDABOT-$branchSha" >> $GITHUB_ENV
      - name: Rename base branch so it will work in our build system
        run: gh api "repos/$GH_REPOSITORY/branches/$BRANCH_NAME/rename" --method POST -f "new_name=$NEW_BRANCH_NAME"

      
